#!/bin/bash
#
# Automaticky vytvori zavislosti pro .c a .h soubory, ktere dostane
# jako argumenty. Vypisuje na stdout.
#

# DEPFILES = jmena souboru, ktere se maji pridat do zavislosti
# kazdeho souboru, typicky Makefile.in

while [ "$1" ] ; do
  echo -n "$1: $DEPFILES"
  sed -n 's:^#include "\(.*\)":\1:p' < "$1" | while read FNAME; do
    echo -n " $FNAME"
  done
  echo
  echo "	touch $1"
  shift 1
done